# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: ghostcompany.github.io
title: Ghost Company
#email: projetoghostcompany@gmail.com
#author: Ghost Company
description: Site desenvolvido para o projeto desenvolvido durante o III Hackfest contra a corrupção do MPPB.
copyright: 'Copyright &copy; 2017 Ghost Company. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
encoding: UTF-8
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
 #- title: twitter
 #  url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/Ghost-Company
 # - title: linkedin
 #   url: 
